OdeToFood/src/OdeToFood/Entities/OdeTFoodDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace OdeToFood.Entities
{
    public class OdeTFoodDbContext : DbContext
    {
        public OdeTFoodDbContext(DbContextOptions options) : base(options)
        {
        }

        public DbSet<Restaurant> Restaurants { get; set; }
    }
}

OdeToFood/src/OdeToFood/Entities/Restaurant.cs
using System.ComponentModel.DataAnnotations;

namespace OdeToFood.Entities
{
    public enum CuisineType
    {
        None,
        Italian,
        French,
        Japenese,
        American
    }

    public class Restaurant
    {
        public int Id { get; set; }

        [Display(Name = "Restaurant Name")]
        [Required, MaxLength(80)]
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

OdeToFood/src/OdeToFood/Models/Restaurant.cs
namespace OdeToFood.Models
{
    public class Restaurant
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

OdeToFood/src/OdeToFood/ViewModels/HomePageViewModel.cs
using OdeToFood.Entities;
using System.Collections.Generic;

namespace OdeToFood.ViewModels
{
    public class HomePageViewModel
    {
        public string CurrentMessage { get; set; }
        public IEnumerable<Restaurant> Restaurants { get; set; }
    }
}

OdeToFood/src/OdeToFood/ViewModels/RestaurantEditViewModel.cs
using OdeToFood.Entities;

namespace OdeToFood.ViewModels
{
    public class RestaurantEditViewModel
    {
        public string Name { get; set; }
        public CuisineType Cuisine { get; set; }
    }
}

OdeToFood/src/OdeToFood/ViewComponents/GreetingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using OdeToFood.Services;

namespace OdeToFood.ViewComponents
{
    public class GreetingViewComponent :ViewComponent
    {
        private IGreeter _greeter;
        public GreetingViewComponent(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            var model = _greeter.GetGreeting();
            return Task.FromResult<IViewComponentResult>(View("Default", model));
        }
    }
}

OdeToFood/src/OdeToFood/Views/Home/Create.cshtml
@model OdeToFood.Entities.Restaurant
@ViewBag.Title = "Create"


<div>
    <h1>Create</h1>
    
    <div>
        
        @using (Html.BeginForm())
        {
            <div>
                @Html.LabelFor(m => m.Name)
                @Html.EditorFor(m => m.Name)
                @Html.ValidationMessageFor(m => m.Name)
            </div>
            <div>
                @Html.LabelFor(m => m.Cuisine)
                @Html.DropDownListFor(m => m.Cuisine, Html.GetEnumSelectList(typeof(CuisineType)))
                @Html.ValidationMessageFor(m => m.Cuisine)
                
            </div>
            <div>
                <input type="submit" value="Save!"/>
            </div>
        }

    </div>

</div>

OdeToFood/src/OdeToFood/Views/Home/Details.cshtml
@ViewBag.Title = @Model.Name

<h1>@Model.Name</h1>
<div>
    @Model.Id
</div>
<div>
    @Model.Cuisine
</div>
<div>
    @Html.ActionLink("Home", "Index")
</div>

OdeToFood/src/OdeToFood/Views/Home/Index.cshtml
@ViewBag.Title = "OdeToFood"
<h1>@Model.CurrentMessage</h1>
<table>
    @foreach (var restuarant in Model.Restaurants)
    {
        <tr>
            <td>
                @Html.ActionLink("View", "Details", new { id = @restuarant.Id })
                <a></a>
            </td>
            <td>@restuarant.Name</td>
        </tr>
    }
</table>

OdeToFood/src/OdeToFood/Views/Shared/Components/Greeting/Default.cshtml
@model string

<div>
    Today's message is : @Model
</div>

OdeToFood/src/OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
<footer>
    @await Component.InvokeAsync("Greeting")
</footer>
</body>
</html>